name: Maven Reusable Workflow

on:
  workflow_dispatch:
  workflow_call:

jobs:
  Maven-Workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml

# Assuming this is a separate workflow file
name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    uses: ./.github/workflows/maven-reusable.yml
